# Generated by Django 5.0.1 on 2024-01-16 08:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_brand",
                    models.CharField(
                        choices=[
                            ("TYT", "Toyota"),
                            ("FRD", "Ford"),
                            ("CHV", "Chevrolet"),
                            ("HND", "Honda"),
                            ("NSN", "Nissan"),
                            ("JEP", "Jeep"),
                            ("HYN", "Hyundai"),
                            ("KIA", "Kia"),
                            ("RAM", "Ram Trucks"),
                            ("SBR", "Subaru"),
                            ("GMC", "GMC"),
                            ("VSW", "Volkswagen"),
                            ("BMW", "BMW"),
                            ("MZD", "Mazda"),
                            ("BNZ", "Mercedes Benz"),
                            ("LXS", "Lexus"),
                            ("TSL", "Tesla"),
                            ("DDG", "Dodge"),
                            ("AUD", "Audi"),
                            ("BUK", "Buick"),
                            ("ACR", "Acura"),
                            ("VLV", "Volvo"),
                            ("CDL", "Cadillac"),
                            ("CRY", "Chrysler"),
                            ("MSH", "Mitsubishi"),
                            ("LND", "Land Rover"),
                            ("LCN", "Lincoln"),
                            ("PCH", "Porsche"),
                            ("INF", "Infiniti"),
                            ("GNS", "Genesis"),
                            ("MIN", "Mini"),
                            ("MSR", "Maserati"),
                            ("AFR", "Alfa Romeo"),
                            ("JGR", "Jaguar"),
                            ("BNT", "Bentley"),
                            ("FRR", "Ferrari"),
                            ("LMB", "Lamborghini"),
                            ("ASM", "Aston Martin"),
                        ],
                        default="TYT",
                        max_length=3,
                    ),
                ),
                ("doors", models.IntegerField(default=4)),
                ("engine_hp", models.IntegerField()),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DSL", "Diesel"),
                            ("PTR", "Petrol"),
                            ("HYB", "Hybrid"),
                            ("ELC", "Electric"),
                            ("BIO", "Biofuels"),
                            ("HDR", "Hydrogen"),
                            ("GAS", "Natural Gas"),
                            ("ETH", "Ethanol"),
                        ],
                        default="PTR",
                        max_length=3,
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                (
                    "model_year",
                    models.IntegerField(
                        default=2024,
                        validators=[
                            django.core.validators.MaxValueValidator(2999),
                            django.core.validators.MinValueValidator(1900),
                        ],
                    ),
                ),
                ("series", models.CharField(max_length=50)),
                (
                    "transmission_speeds",
                    models.IntegerField(
                        default=6,
                        validators=[django.core.validators.MaxValueValidator(18)],
                    ),
                ),
                (
                    "transmission_style",
                    models.CharField(
                        choices=[
                            ("MNU", "Manual"),
                            ("ATO", "Automatic"),
                            ("TPT", "Tiptronic"),
                            ("SMA", "Semi-Automatic"),
                            ("DCL", "Dual-Clutch"),
                            ("CVT", "Continuously Variable Transmission"),
                        ],
                        default="MNU",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exterior_color",
                    models.CharField(
                        choices=[
                            ("WHI", "white"),
                            ("BLK", "black"),
                            ("GRY", "gray"),
                            ("SLV", "silver"),
                            ("BLU", "blue"),
                            ("RED", "red"),
                            ("BRW", "brown"),
                            ("GRN", "green"),
                            ("ORG", "orange"),
                            ("BIG", "beige"),
                            ("PRP", "purple"),
                            ("GLD", "gold"),
                            ("YLW", "yellow"),
                        ],
                        default="WHI",
                        max_length=3,
                    ),
                ),
                ("mileage", models.IntegerField(default=0)),
                ("vin", models.CharField(max_length=17)),
                ("listed", models.DateField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="garage.car"
                    ),
                ),
            ],
        ),
    ]
