# Generated by Django 5.0.1 on 2024-01-18 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_alter_carad_listed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carad",
            name="listed",
            field=models.DateTimeField(
                default=datetime.date.today, verbose_name="Listed On"
            ),
        ),
    ]
