# Generated by Django 5.0.1 on 2024-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0004_car_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="carad",
            name="true_car_link",
            field=models.URLField(
                blank=True, verbose_name="Ad Link in TrueCar Website"
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="listed",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Listed On"),
        ),
        migrations.AlterField(
            model_name="carad",
            name="vin",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
