# Generated by Django 5.0.1 on 2024-01-24 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0005_carad_true_car_link_alter_carad_listed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="listed",
        ),
    ]
