# Generated by Django 5.0.1 on 2024-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0006_remove_car_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="carad",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
