# Generated by Django 5.0.1 on 2024-01-24 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0007_carad_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carad",
            name="listed",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 19, 25, 21, 429767),
                verbose_name="Listed On",
            ),
        ),
    ]
