# Generated by Django 5.0.1 on 2024-01-24 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0008_alter_carad_listed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carad",
            name="exterior_color",
            field=models.CharField(
                choices=[
                    ("WHI", "white"),
                    ("BLK", "black"),
                    ("GRY", "gray"),
                    ("SLV", "silver"),
                    ("BLU", "blue"),
                    ("RED", "red"),
                    ("BRW", "brown"),
                    ("GRN", "green"),
                    ("ORG", "orange"),
                    ("BIG", "beige"),
                    ("PRP", "purple"),
                    ("GLD", "gold"),
                    ("YLW", "yellow"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="listed",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 19, 26, 35, 487876),
                verbose_name="Listed On",
            ),
        ),
    ]
