# Generated by Django 5.0.1 on 2024-01-24 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0009_alter_carad_exterior_color_alter_carad_listed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carad",
            name="exterior_color",
            field=models.CharField(default="White", max_length=3),
        ),
        migrations.AlterField(
            model_name="carad",
            name="listed",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 19, 56, 29, 785638),
                verbose_name="Listed On",
            ),
        ),
    ]
